name: automated-testing-integration

on:
  push:
    branches:
      - main

  schedule:
    - cron: "00 13 * * TUE"
  workflow_dispatch:

env:
  project_name: "frontend-automation-framework"
  language: "java"

jobs:
  integration-frontend-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Run frontend E2E test
        run: ./gradlew build

      - name: Generate reports
        run: ./gradlew reports
      - name: Upload reports automation testing
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: testing-reports
          path: |
            target/site/serenity/serenity-summary.html
            target/site/serenity/results.csv
          retention-days: 1